import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:recorder_poc/pine_palette.dart';
import 'package:recorder_poc/pine_theme.dart';

enum PineIconSize {
  XXXXSMALL,
  XXXSMALL,
  XXSMALL,
  XXMSMALL,
  XSMALL,
  SMALL,
  XLSMALL,
  XXLSMALL,
  SMALL_MEDIUM,
  SMALL_TINY,
  MEDIUM,
  MEDIUM_SMALL,
  LARGE,
  XSLARGE,
  SLARGE,
  MLARGE,
  XMEDIUM_SMALL,
  XLARGE,
  XXLARGE,
  XXSLARGE,
  XXXLARGE,
  XXXSLARGE,
  XXXMLARGE,
  XXXXLARGE,
  XXXXXLARGE,
  XHUGE,
  XXHUGE,
}

const _icons = <String, String>{
  'ADD': 'assets/icons/add.svg',
  'ADD_GREEN': 'assets/icons/add_enable.svg',
  'ADD_GREEN_CIRCLE': 'assets/icons/add_green_circle.svg',
  'ADD_CIRCLE_ORANGE': 'assets/icons/add_circle_orange.svg',
  'ALARM': 'assets/icons/alarm.svg',
  'ALERT': 'assets/icons/alert.svg',
  'ALERT_ORANGE': 'assets/icons/alert_orange.svg',
  'ALTERNATIVE_TOKEN': 'assets/icons/alternative_token_icon.svg',
  'ALLERGIES': 'assets/icons/allergies.svg',
  'APPOINTMENTS_FILLED': 'assets/icons/appointments_filled.svg',
  'APPOINTMENTS_UNFILLED': 'assets/icons/appointments_unfilled.svg',
  'APPOINTMENT_DIAGNOSTIC': 'assets/icons/appintment_diagnostic.svg',
  'APPOINTMENT_SENT': 'assets/icons/appointment_sent.svg',
  'APPT_USER_PLACEHOLDER': 'assets/icons/appt_user_placeholder.svg',
  'ARROW': 'assets/icons/arrow.svg',
  'ARROW_SLIM': 'assets/icons/arrow_slim.svg',
  'ARROW_DOWN': 'assets/icons/arrow_down.svg',
  'ARROW_DOWN_GREEN': 'assets/icons/arrow_down_green.svg',
  'ARROW_GREEN': 'assets/icons/arrow_green.svg',
  'ARROW_LEFT': 'assets/icons/arrow_left.svg',
  'ARROW_LEFT_GREEN': 'assets/icons/arrow_left_green.svg',
  'ARROW_RIGHT_GREEN': 'assets/icons/arrow_right_green.svg',
  'ARROW_RIGHT_LONG_GREEN_ICON': 'assets/icons/arrow_right_long.svg',
  'ARROW_UP_GREEN': 'assets/icons/arrow_up_green.svg',
  'ATTACH': 'assets/icons/attach.svg',
  'AVAILABILITY_GREEN': 'assets/icons/availability_green.svg',
  'AVATAR_OUTLINED_GREEN': 'assets/icons/avatar_outlined_green.svg',
  'BAND_AID_OUTLINE_GREEN': 'assets/icons/band_aid_outline_green.svg',
  'BANNER_ALERT': 'assets/icons/banner_alert.svg',
  'BELL_ICON': 'assets/icons/bell_icon.svg',
  'BIG_CALENDAR': 'assets/icons/big_calendar.svg',
  'BIG_CHECK': 'assets/icons/big_check.svg',
  'BIG_CLIPBOARD': 'assets/icons/big_clipboard.svg',
  'BIG_CLIPBOARD1': 'assets/icons/big_clipboard_bg1.svg',
  'BIG_CLIPBOARD2': 'assets/icons/big_clipboard_bg2.svg',
  'BIG_INSURANCE_CARD': 'assets/icons/big_insurance_card.svg',
  'BILL_WHITE': 'assets/icons/bill_white.svg',
  'BLUE_INFORMATION': 'assets/icons/information_blue.svg',
  'BLUE_INFORMATION_ROUNDED': 'assets/icons/information_blue_rounded.svg',
  'BOARD': 'assets/icons/board.svg',
  'BOARD_WHITE': 'assets/icons/white_board.svg',
  'BONE_WHITE': 'assets/icons/bone_white.svg',
  'BOOKMARK_FILLED_BAPTIST_GREEN': 'assets/icons/bookmark_filled_baptist_green.svg',
  'BOOKMARK_GREEN': 'assets/icons/bookmark_green_outlined.svg',
  'BOOKMARK_GREEN_FILLED': 'assets/icons/bookmark_green_filled.svg',
  'BOOKMARK_MODAL': 'assets/icons/bookmark_modal.svg',
  'BOOKMARK_NO_RESULTS': 'assets/icons/bookmark_no_results.svg',
  'BOOK_AN_APPOINTMENT_FILLED': 'assets/icons/book_an_appointment_filled.svg',
  'BOOK_AN_APPOINTMENT_UNFILLED': 'assets/icons/book_an_appointment_unfilled.svg',
  'BOOK_VISIT': 'assets/icons/book_visit.svg',
  'BREAST_FEEDING': 'assets/icons/breast_feeding.svg',
  'BROWSE_LOCATION': 'assets/icons/browse_location.svg',
  'BROWSE_LOCATIONS_FILLED': 'assets/icons/browse_locations_filled.svg',
  'BROWSE_LOCATIONS_UNFILLED': 'assets/icons/browse_locations_unfilled.svg',
  'CALENDAR': 'assets/icons/calendar.svg',
  'CALENDAR_APPOINTMENT': 'assets/icons/calendar_appointment.svg',
  'CALENDAR_APPOINTMENT_VERIFICATION': 'assets/icons/calendar_appointment_verification.svg',
  'CALENDAR_BLACK': 'assets/icons/calendar_black.svg',
  'CALENDAR_GREEN': 'assets/icons/calendar_green.svg',
  'CALENDAR_ICON': 'assets/icons/calendar_icon.svg',
  'CALENDAR_REMINDER': 'assets/icons/calendar_reminder.svg',
  'CALENDAR_REMINDER_PROCEDURE': 'assets/icons/calendar_reminder_procedure.svg',
  'CALENDAR_WHITE': 'assets/icons/calendar_white.svg',
  'CALL': 'assets/icons/call.svg',
  'CAMERA': 'assets/icons/camera.svg',
  'CAMERA_APPOI_EQUIPMENT': 'assets/icons/camera_appointment.svg',
  'CAMERA_EQUIPMENT': 'assets/icons/camera_equipment.svg',
  'CAMERA_GRAY': 'assets/icons/camera_gray.svg',
  'CAMERA_OUTLINE': 'assets/icons/camera_outline.svg',
  'CAMERA_TEST': 'assets/icons/camera_test.svg',
  'CAMERA_WHITE': 'assets/icons/camera_white.svg',
  'CARE_GUIDANCE': 'assets/icons/care_guidance.svg',
  'CARE_PHONE': 'assets/icons/care_phone.svg',
  'CARE_PREF_FILLED': 'assets/icons/care_pref_filled.svg',
  'CARE_PREF_UNFILLED': 'assets/icons/care_pref_unfilled.svg',
  'CHARITY': 'assets/icons/charity.svg',
  'CHARITY_OUTLINE': 'assets/icons/charity_outline.svg',
  'CHAT': 'assets/icons/chat.svg',
  'CHAT_FILLED_BAPTIST_GREEN': 'assets/icons/chat_filled_baptist_green.svg',
  'CHAT_FILLED_WHITE': 'assets/icons/chat_filled_white.svg',
  'CHECK': 'assets/icons/success_check.svg',
  'CHECKED_ICON': 'assets/icons/checked_icon.svg',
  'CHECK_BOLD': 'assets/icons/check_bold.svg',
  'CHECK_BOLD_SUCCESS': 'assets/icons/check_bold_success.svg',
  'CHECK_CIRCLE': 'assets/icons/check_circle.svg',
  'CHECK_CIRCLE_SMALL': 'assets/icons/check_circle_small.svg',
  'CHECK_FILLED': 'assets/icons/check_filled.svg',
  'CHECK_FILLED_GREEN': 'assets/icons/check_filled_green.svg',
  'CHECK_GREYED': 'assets/icons/check_grey.svg',
  'CHECK_LIST_WHITE': 'assets/icons/check_list_white.svg',
  'CHECK_OK_CIRCLE': 'assets/icons/check_ok_circle.svg',
  'CHECK_OK_GREEN': 'assets/icons/green_ok.svg',
  'CLEAR': 'assets/icons/clear.svg',
  'CLEAR_WITHOUT_BACKGROUND': 'assets/icons/clear_without_background.svg',
  'CLINICAL_INFO': 'assets/icons/clinical_info.svg',
  'CLINICAL_NOTES_SOLID': 'assets/icons/clinical_notes_solid.svg',
  'CLINICAL_VITALS': 'assets/icons/clinical_vitals.svg',
  'CLINICAL_VITALS_FILTER': 'assets/icons/clinical_vitals_filter.svg',
  'CLINICAL_VITALS_WHITE': 'assets/icons/clinical_vitals_white.svg',
  'CLIPBOARD': 'assets/icons/clipboard.svg',
  'CLIPBOARD_WHITE': 'assets/icons/clipboard_icon_white.svg',
  'CLOCK_BLACK': 'assets/icons/clock_black.svg',
  'CLOSE': 'assets/icons/close.svg',
  'CLOSE_CROSS': 'assets/icons/close_circle.svg',
  'CLOSE_GRAY': 'assets/icons/close_gray.svg',
  'CLOSE_RED': 'assets/icons/close_red.svg',
  'COMMENT': 'assets/icons/comment.svg',
  'CONNECTIVITY': 'assets/icons/connectivity.svg',
  'CONSENT_FOR_SERVICE': 'assets/icons/consent_for_services.svg',
  'CONTACT_MAIL': 'assets/icons/emergency_contact_mail.svg',
  'CONTACT_PHONE': 'assets/icons/emergency_contact_phone.svg',
  'CREDENTIAL_PERSON': 'assets/icons/credential_person.svg',
  'CREDIT_CARDS': 'assets/icons/credit_cards.svg',
  'CROSS': 'assets/icons/cross.svg',
  'CROSS_FILLED': 'assets/icons/cross_filled.svg',
  'CROSSED_EYE': 'assets/icons/crossed_eye.svg',
  'CROSS_FILLED_WHITE': 'assets/icons/cross_filled_white.svg',
  'CROSS_GREY': 'assets/icons/cross_grey.svg',
  'CROSS_RED': 'assets/icons/red_plus.svg',
  'CURRENT_LOCATION': 'assets/icons/current_location.svg',
  'DELETE': 'assets/icons/delete.svg',
  'DIAGNOSTIC_APPOINTMENT_SENT': 'assets/icons/diagnostic_appointment_sent.svg',
  'DIAGNOSTIC_IMAGES': 'assets/icons/diagnostic_images.svg',
  'DIAGNOSTIC_ORDER_CAPTURE': 'assets/icons/diagnostic_order_capture.svg',
  'DIAGNOSTIC_ORDER_CLOSE': 'assets/icons/diagnostic_referral_order_close_icon.svg',
  'DIAGNOSTIC_ORDER_COUNT': 'assets/icons/diagnostic_order_count.svg',
  'DIAGNOSTIC_ORDER_FILE': 'assets/icons/diagnostic_order_file.svg',
  'DIAGNOSTIC_ORDER_GALLERY': 'assets/icons/diagnostic_order_gallery.svg',
  'DIAGNOSTIC_ORDER_RETURN': 'assets/icons/diagnostic_order_return.svg',
  'DIAGNOSTIC_ORDER_RIGHT_ARROW': 'assets/icons/diagnostic_order_right_arrow.svg',
  'DIAGNOSTIC_RESULTS': 'assets/icons/diagnostic_results.svg',
  'DIAGNOSTIC_RESULTS_FILLED': 'assets/icons/diagnostic_results_filled.svg',
  'DIAGNOSTIC_RESULTS_ICON': 'assets/icons/diagnostic_results_icon.svg',
  'DIET_NUTRITION': 'assets/icons/diet_and_nutrition.svg',
  'DIGITAL_CONSENT_WHITE': 'assets/icons/digital_consent.svg',
  'DIRECTIONS': 'assets/icons/directions.svg',
  'DOCTOR': 'assets/icons/doctor.svg',
  'DOCTOR_NEW': 'assets/icons/doctor_new_icon.svg',
  'DOCTOR_WHITE': 'assets/icons/doctor_white.svg',
  'DOCUMENTS': 'assets/icons/your_rights_and_protections.svg',
  'DOCUMENTS_FILLED': 'assets/icons/documents_filled.svg',
  'DOCUMENTS_WHITE': 'assets/icons/documents.svg',
  'DOCUMENT_CENTER_OUTLINE': 'assets/icons/document_center_outline.svg',
  'DOCUMENT_CENTER_SOLID': 'assets/icons/document_center_solid.svg',
  'DOT': 'assets/icons/dot.svg',
  'DOWNLOAD_FILLED': 'assets/icons/download.svg',
  'DRUGS': 'assets/icons/drugs.svg',
  'DRUG_KNOWLEDGE_BASE': 'assets/icons/drug_knowledge_base.svg',
  'EDIT': 'assets/icons/edit.svg',
  'EMAIL_ICON': 'assets/icons/email_icon.svg',
  'EMERGENCY': 'assets/icons/emergency.svg',
  'EMERGENCY_URGENT_CARE': 'assets/icons/emergency_urgent_care.svg',
  'ERROR': 'assets/icons/error.svg',
  'ERROR_CIRCULAR': 'assets/icons/error_circular.svg',
  'ERROR_X': 'assets/icons/error_x_login.svg',
  'EXCLAMATION': 'assets/icons/exclamation.svg',
  'EYE': 'assets/icons/eye.svg',
  'FACEBOOK': 'assets/icons/facebook.svg',
  'FAQ_ICON': 'assets/icons/faq_icon.svg',
  'FINGERPRINT': 'assets/icons/fingerprint.svg',
  'FOLDERS_SOLID': 'assets/icons/folders_solid.svg',
  'FOURTH_APPOINTMENT_CARD': 'assets/icons/fourth_appointment_card.svg',
  'FOURTH_DIAGNOSTIC_APPOINTMENT_CARD': 'assets/icons/forth_diagnostic_card.svg',
  'FOURTH_LAB_RESULT_CARD': 'assets/icons/fourth_lab_result_card.svg',
  'FOURTH_MEDICAL_REMINDER_RESULT_CARD': 'assets/icons/fourth_medical_reminder_result_card.svg',
  'FULL': 'assets/icons/full.svg',
  'GET_CARE_FILLED': 'assets/icons/get_care_filled.svg',
  'GET_CARE_UNFILLED': 'assets/icons/get_care_unfilled.svg',
  'GLOBALIZATION': 'assets/icons/globalization.svg',
  'GREEN_CROSS_SMALL': 'assets/icons/cross_green_small.svg',
  'GREEN_INFORMATION': 'assets/icons/information_i.svg',
  'GREEN_PROFILE_ICON': 'assets/icons/green_profile_icon.svg',
  'GUEST': 'assets/icons/guest_icon.svg',
  'HAMBURGER_MENU': 'assets/icons/hamburger_menu.svg',
  'HEALTH': 'assets/icons/health.svg',
  'HEALTH_BOOK': 'assets/icons/health_book.svg',
  'HEALTH_BOOK_MENU': 'assets/icons/health_book_menu.svg',
  'HEALTH_BORDER_GREEN': 'assets/icons/heart_menu.svg',
  'HEALTH_CONDITIONS': 'assets/icons/health_conditions.svg',
  'HEALTH_FILLED_BAPTIST_GREEN': 'assets/icons/heart_fill_baptist_green.svg',
  'HEALTH_FILLED_WHITE': 'assets/icons/health_filled_white.svg',
  'HEALTH_RECORDS_FILLED': 'assets/icons/health_records_filled.svg',
  'HEALTH_RECORDS_UNFILLED': 'assets/icons/health_records_unfilled.svg',
  'HEART_BEAT': 'assets/icons/heartbeat.svg',
  'HEART_FILLED': 'assets/icons/heart_fill.svg',
  'HEART_FILLED_BAPTIST_GREEN': 'assets/icons/heart_fill_baptist_green.svg',
  'HOME': 'assets/icons/home.svg',
  'HOME_FILLED': 'assets/icons/home_filled.svg',
  'HOME_FILLED_BAPTIST_GREEN': 'assets/icons/home_filled_baptist_green.svg',
  'HOME_FILLED_WHITE': 'assets/icons/home_filled_white.svg',
  'HOME_SEARCH_RESULTS': 'assets/icons/home_search_results.svg',
  'HOME_UNFILLED': 'assets/icons/home_unfilled.svg',
  'HOSPITAL': 'assets/icons/hospital.svg',
  'HORIZONTAL_BAR': 'assets/icons/horizontal_bar.svg',
  'IMMUNIZATIONS': 'assets/icons/immunizations.svg',
  'INFO': 'assets/icons/info.svg',
  'INFORMATION_ICON_BLACK': 'assets/icons/information_black.svg',
  'INSTAGRAM': 'assets/icons/instagram.svg',
  'INSURANCE_CARD': 'assets/icons/insurance_card.svg',
  'INSURANCE_CARD_EMPTY': 'assets/icons/insurance_card_empty.svg',
  'INSURANCE_WARNING': 'assets/icons/insurance_warning.svg',
  'IN_OFFICE_VISIT': 'assets/icons/in_office_visit.svg',
  'IN_OFFICE_VISIT_CTA': 'assets/icons/in_office_visit_cta.svg',
  'LAB_RESULTS_FILLED': 'assets/icons/lab_results_filled.svg',
  'LAB_RESULTS_UNFILLED': 'assets/icons/lab_results_unfilled.svg',
  'LAB_RESULTS_WHITE': 'assets/icons/lab_results.svg',
  'LAB_RESULT_MENU': 'assets/icons/lab_result_menu.svg',
  'LAB_RESULT_TOOLTIP': 'assets/icons/lab_result_tooltip.svg',
  'LANGUAGE': 'assets/icons/language.svg',
  'LANGUAGE_WHITE': 'assets/icons/language_white.svg',
  'LEAVE_APP': 'assets/icons/leave_app.svg',
  'LENS_FILLED': 'assets/icons/lens_filled.svg',
  'LINKEDIN': 'assets/icons/linkedin.svg',
  'LIST': 'assets/icons/list.svg',
  'LOCATION': 'assets/icons/location.svg',
  'LOCATION_AVATAR_MINI': 'assets/icons/location_avatar_mini.svg',
  'LOG_OUT': 'assets/icons/log_out.svg',
  'MAMMOGRAPHY_FILLED': 'assets/icons/mammography_filled.svg',
  'MAMMOGRAPHY_UNFILLED': 'assets/icons/mammography_unfilled.svg',
  'MAMMO_RIBBON': 'assets/icons/mammo_ribbon.svg',
  'MAP': 'assets/icons/map_pin_no_location.svg',
  'MEDICARE_OUTPATIENT': 'assets/icons/medicare_outpatient.svg',
  'MEDICATIONS_FILLED': 'assets/icons/medications_filled.svg',
  'MEDICATIONS_UNFILLED': 'assets/icons/medications_unfilled.svg',
  'MEDICINE': 'assets/icons/medicine.svg',
  'MENTAL_HEALTH': 'assets/icons/mental_health.svg',
  'MESSAGE_CENTER': 'assets/icons/message_center.svg',
  'MESSAGE_CENTER_WARNING': 'assets/icons/message_center_warning.svg',
  'MESSAGE_ICON': 'assets/icons/message_icon.svg',
  'MESSAGE_POPUP_WAITING_ROOM': 'assets/icons/message_popup_waiting_room.svg',
  'MESSAGE_WAITING_ROOM': 'assets/icons/message_waiting_room.svg',
  'MICROPHONE': 'assets/icons/microphone.svg',
  'MICROPHONE_APPOINMENT_GREEN': 'assets/icons/microphone_appoinment_green.svg',
  'MICROPHONE_GREEN': 'assets/icons/microphone_green.svg',
  'MICROPHONE_NOT_LISTEN': 'assets/icons/microphone_not_listen.svg',
  'MICROPHONE_OFF': 'assets/icons/microphone_off.svg',
  'MICROPHONE_RED': 'assets/icons/microphone_red.svg',
  'MOBILE_DIAGNOSTIC_IMAGE': 'assets/icons/mobile_diagnostic_image.svg',
  'MONEY_ICON': 'assets/icons/money_icon.svg',
  'MORE_ARROW': 'assets/icons/more_arrow.svg',
  'MORE_ARROW_DOWN': 'assets/icons/more_arrow_down.svg',
  'MORE_ARROW_GRAY': 'assets/icons/more_arrow_gray.svg',
  'MORE_HEALTH_RECORD_SHARING': 'assets/icons/more_health_record_sharing.svg',
  'MY_BAPTIST_HEALTH_FILLED': 'assets/icons/my_baptist_health_filled.svg',
  'MY_BAPTIST_HEALTH_UNFILLED': 'assets/icons/my_baptist_health_unfilled.svg',
  'MY_HEALTH_FILLED': 'assets/icons/my_health_filled.svg',
  'MY_HEALTH_UNFILLED': 'assets/icons/my_health_unfilled.svg',
  'MY_INFORMATION': 'assets/icons/my_information.svg',
  'MY_INFORMATION_NEW': 'assets/icons/my_information_new.svg',
  'NEED_CARE_GUIDE': 'assets/icons/need_care_guide.svg',
  'NOTRESULT': 'assets/icons/not_result.svg',
  'NOT_FOUND': 'assets/icons/not_found.svg',
  'NO_ENTRIES': 'assets/icons/no_entries.svg',
  'NO_ENTRIES_MEDICATIONS': 'assets/icons/no_results_found.svg',
  'NO_MESSAGES': 'assets/icons/no_message.svg',
  'NO_REMINDERS': 'assets/icons/no_reminders.svg',
  'NO_RESULTS_FOUND': 'assets/icons/no_results_found.svg',
  'NO_RESULTS_FOUND_DIAGNOSTIC': 'assets/icons/no_result_diagnostic.svg',
  'NO_RESULTS_FOUND_VISITED_FACILITIES': 'assets/icons/no_result_visited_facilities.svg',
  'ONBOARD_FACE_ID': 'assets/icons/on_board_faceid.svg',
  'ONBOARD_HEALTH_JOURNAL': 'assets/icons/health_journal.svg',
  'ONBOARD_LONG_PRESS': 'assets/icons/on_board_long_press.svg',
  'ONBOARD_MAP': 'assets/icons/board_location.svg',
  'ONBOARD_NOTIFICATION': 'assets/icons/board_notification.svg',
  'OPTIONS_LINE_FILLED': 'assets/icons/options.svg',
  'ORTHOPEDIC_APPT_SPECIALIST': 'assets/icons/orthopedic_appt_specialist.svg',
  'ORTHOPEDIC_SPORT_MEDICINE': 'assets/icons/orthopedic_appt_sport.svg',
  'PATIENT_RESOURCES': 'assets/icons/patient_resources.svg',
  'PAY_MY_BILL': 'assets/icons/pay_my_bill.svg',
  'PAY_MY_BILL_NEW': 'assets/icons/pay_my_bill_new_icon.svg',
  'PAY_MY_BILL_UNFILLED': 'assets/icons/pay_my_bill_unfilled.svg',
  'PAY_MY_BILL_WALLET': 'assets/icons/pay_my_bill_wallet.svg',
  'PEDIATRIC_URGENT_CARE': 'assets/icons/ped_urgent_care.svg',
  'PEN': 'assets/icons/pen.svg',
  'PENCIL': 'assets/icons/pencil.svg',
  'PEOPLE_WHITE': 'assets/icons/people_white.svg',
  'PERSON': 'assets/icons/person.svg',
  'PHARMACY': 'assets/icons/pharmacy.svg',
  'PHARMACY_BENEFITS': 'assets/icons/pharmacy_benefits.svg',
  'PHONE': 'assets/icons/phone.svg',
  'PHONE_GREEN': 'assets/icons/phone_green.svg',
  'PILL': 'assets/icons/pill.svg',
  'PILLS_WHITE': 'assets/icons/pills_icon_white.svg',
  'PILL_DISABLED': 'assets/icons/pill_disabled.svg',
  'PINEAPPLE': 'assets/icons/pineapple.svg',
  'PINEAPPLE_BLUE': 'assets/icons/pineapple_blue.svg',
  'PINEAPPLE_LIGHT': 'assets/icons/pineapple_light.svg',
  'PINEAPPLE_LOGO': 'assets/icons/pineapple_logo.svg',
  'PINEAPPLE_WEB_ICON': 'assets/icons/pineapple_white_bkg.svg',
  'PINEAPPLE_WHITE': 'assets/icons/pineapple_white.svg',
  'PIN_OUTLINE_GREEN': 'assets/icons/pin_outline_green.svg',
  'PROCEDURES_ICON': 'assets/icons/procedures.svg',
  'PROCEDURES_ON_BOARDING': 'assets/icons/procedures_on_boarding.svg',
  'PROCEDURES_SEARCH_NO_RESULT': 'assets/icons/no_search_result_icon.svg',
  'PROCEDURE_FILTER': 'assets/icons/filter.svg',
  'PROFILE': 'assets/icons/profile.svg',
  'PROFILE_FILL': 'assets/icons/profile_fill.svg',
  'PROFILE_FILL_2': 'assets/icons/profile_fill_2.svg',
  'PROFILE_FILLED_WHITE': 'assets/icons/profile_filled_white.svg',
  'PROFILE_GREY_COLOR': 'assets/icons/profile_grey_color.svg',
  'PROFILE_ICON': 'assets/icons/profile_icon.svg',
  'PROFILE_ICON_GREEN': 'assets/icons/profile_green.svg',
  'PROVIDER_LOCATION': 'assets/icons/provider_location.svg',
  'PROVIDER_PHONE': 'assets/icons/provider_phone.svg',
  'PSYCHIATRY': 'assets/icons/psychiatry.svg',
  'REFILL_NOTICE': 'assets/icons/refill_notice.svg',
  'REFRESH': 'assets/icons/refresh.svg',
  'REMINDERS_BADGE_ICON': 'assets/icons/reminder_badge_icon.svg',
  'REMINDERS_PROFILE_ICON': 'assets/icons/reminders_profile_icon.svg',
  'REMOVE': 'assets/icons/remove.svg',
  'RENEW_MY_PRESCRIPTION': 'assets/icons/renew_my_prescription.svg',
  'RESOURCES': 'assets/icons/resources.svg',
  'RESOURCES_BOOKMARK': 'assets/icons/resources_bookmark.svg',
  'RESOURCES_FILLED': 'assets/icons/resources_filled.svg',
  'RESOURCES_FILLED_BAPTIST_GREEN': 'assets/icons/resources_filled_baptist_green.svg',
  'RESOURCES_FILLED_WHITE': 'assets/icons/resources_filled_white.svg',
  'RESOURCES_UNFILLED': 'assets/icons/resources_unfilled.svg',
  'REVOKE_GREEN': 'assets/icons/revoke_green.svg',
  'RIBBON': 'assets/icons/ribbon.svg',
  'RIBBON_OUTLINE_GREEN': 'assets/icons/ribbon_outline_green.svg',
  'SEARCH': 'assets/icons/search.svg',
  'SEARCH_DOCUMENT_OUTLINE': 'assets/icons/search_document_outline.svg',
  'SECURE': 'assets/icons/secure.svg',
  'SEND_MESSAGE': 'assets/icons/send_message.svg',
  'SETTINGS': 'assets/icons/settings.svg',
  'SHARE_HEALTH_GREEN': 'assets/icons/share_health_green.svg',
  'SHARE_RECORDS': 'assets/icons/share_records.svg',
  'SHARING_HEALTH_RECORD_ICON': 'assets/icons/sharing_health_record_icon.svg',
  'SHARING_ICON': 'assets/icons/shraring icon.svg',
  'SHIELD': 'assets/icons/shield.svg',
  'SLASH': 'assets/icons/slash.svg',
  'SMART_HEALTH_CARD_WHITE': 'assets/icons/smart_health_card.svg',
  'SPAIN_FLAG': 'assets/icons/spain_flag.svg',
  'STAR': 'assets/icons/star.svg',
  'STAR_FILLED': 'assets/icons/star_filled.svg',
  'STAR_GREEN': 'assets/icons/star_green.svg',
  'STETHO_SCOPE': 'assets/icons/stetho_scope.svg',
  'STETHOSCOPE': 'assets/icons/stethoscope.svg',
  'SURVEY': 'assets/icons/survey.svg',
  'SUBTRACT_CIRCLE': 'assets/icons/subtract_circle.svg',
  'TELEPHONE_CALL': 'assets/icons/telephone_call.svg',
  'TIME': 'assets/icons/hour.svg',
  'TIME_THIN': 'assets/icons/time.svg',
  'TIP': 'assets/icons/tip.svg',
  'TOOLTIP_ICON': 'assets/icons/toast.svg',
  'TRASH_CAN': 'assets/icons/trash_can.svg',
  'TWITTER': 'assets/icons/twitter.svg',
  'UPLOAD_IMAGE_INFO_TOAST_ICON': 'assets/icons/toast_green.svg',
  'URGENT_CARE': 'assets/icons/urgent_care_icon.svg',
  'URGENT_CARE_CHECK_IN': 'assets/icons/urgent_care_check_in_icon.svg',
  'URGENT_CARE_FILLED': 'assets/icons/urgent_care_filled.svg',
  'URGENT_CARE_UNFILLED': 'assets/icons/urgent_care_unfilled.svg',
  'US_FLAG': 'assets/icons/us_flag.svg',
  'VIDEO_CALL': 'assets/icons/video_call.svg',
  'VIDEO_VISITS': 'assets/icons/video_visits_icon.svg',
  'VIDEO_ZOOM': 'assets/icons/video_zoom.svg',
  'VIRTUAL_VISIT__MESSAGE_CENTER__MESSAGE_DETAIL_PAGE_ATTACHMENT': 'assets/icons/attachment.svg',
  'VIRTUAL_VISIT__MESSAGE_CENTER__MESSAGE_DETAIL_PAGE_DOWNLOAD': 'assets/icons/download.svg',
  'VIRTUAL_VISIT__MESSAGE_CENTER__MESSAGE_DETAIL_PAGE_DOWNLOAD_ATTACHMENT_ERROR': 'assets/icons/error_x_vv_attachment_download.svg',
  'VISIBILITY_OFF_FILLED': 'assets/icons/visibility_off_icon.svg',
  'WAIT_INDICATOR': 'assets/icons/wait_indicator.svg',
  'WAIT_INDICATOR_WHITE': 'assets/icons/wait_indicator_white.svg',
  'WALLET': 'assets/icons/wallet.svg',
  'WALLET_UNFILLED': 'assets/icons/wallet_unfilled.svg',
  'WARNING': 'assets/icons/warning.svg',
  'WARNING_ORANGE': 'assets/icons/warning_orange.svg',
  'WHATS_NEW_SCREEN_ONE': 'assets/icons/whats_new_screen_one.svg',
  'WHATS_NEW_SCREEN_TWO': 'assets/icons/whats_new_screen_two.svg',
  'WHOLE_BLUE_INFORMATION': 'assets/icons/round_exclamation.svg',
  'WIFI': 'assets/icons/wifi.svg',
  'WIFI_APPOINTMENT_CONNECTED': 'assets/icons/wifi_appointment_green.svg',
  'WIFI_CONNECTED': 'assets/icons/wifi_green.svg',
  'WIFI_DISCONNECTED': 'assets/icons/wifi_red.svg',
  'WIFI_GRAY': 'assets/icons/wifi_gray.svg',
  'WIFI_GRAY_': 'assets/icons/wifi_gray_.svg',
  'WIFI_NEW_GREEN': 'assets/icons/wifi_new_green.svg',
  'WIFI_YELLOW': 'assets/icons/wifi_yellow.svg',
  'WOMAN_ONLINE_GREEN': 'assets/icons/woman_online_green.svg',
  'WORK': 'assets/icons/work.svg',
  'X_ERROR': 'assets/icons/error_x.svg',
  'VIRTUAL_VISIT': 'assets/icons/virtual_visit_icon.svg',
  'YOUTUBE': 'assets/icons/youtube.svg',
  'ENDO': 'assets/icons/endocrinology_icon.svg',
};

const _iconSize = {
  PineIconSize.XXXXSMALL: 4.0,
  PineIconSize.XXXSMALL: 10.0,
  PineIconSize.XXSMALL: 12.0,
  PineIconSize.XXMSMALL: 14.0,
  PineIconSize.XSMALL: 16.0,
  PineIconSize.XLSMALL: 19.0,
  PineIconSize.XXLSMALL: 24.0,
  PineIconSize.SMALL: 34.0,
  PineIconSize.SMALL_MEDIUM: 39.0,
  PineIconSize.SMALL_TINY: 22.0,
  PineIconSize.MEDIUM_SMALL: 25.0,
  PineIconSize.XMEDIUM_SMALL: 28.0,
  PineIconSize.MEDIUM: 47.0,
  PineIconSize.LARGE: 50.0,
  PineIconSize.XSLARGE: 55.0,
  PineIconSize.SLARGE: 68.0,
  PineIconSize.MLARGE: 75.0,
  PineIconSize.XLARGE: 98.0,
  PineIconSize.XXLARGE: 136.0,
  PineIconSize.XXSLARGE: 110.0,
  PineIconSize.XXXLARGE: 144.0,
  PineIconSize.XXXSLARGE: 145.7,
  PineIconSize.XXXMLARGE: 150.0,
  PineIconSize.XXXXLARGE: 172.0,
  PineIconSize.XXXXXLARGE: 200.0,
  PineIconSize.XHUGE: 240.0,
  PineIconSize.XXHUGE: 300.0,
};

final _iconColor = {
  PineThemeTypes.COMMON: PineTheme.colors.common.icon,
  PineThemeTypes.PRIMARY: PineTheme.colors.primary.icon,
  PineThemeTypes.SECONDARY: PineTheme.colors.secondary.icon,
  PineThemeTypes.CUSTOM: PineTheme.colors.custom.icon,
  PineThemeTypes.LIGHT: PineTheme.colors.light.icon,
  PineThemeTypes.DARK: PinePalette.black,
  PineThemeTypes.ERROR: PinePalette.alertRed,
  PineThemeTypes.ERROR_YELLOW: PinePalette.yellow,
  PineThemeTypes.ICON_BLUE: PinePalette.blueMessage
};

class PineIcon extends StatelessWidget {
  const PineIcon({
    Key? key,
    required this.icon,
    this.padding = const EdgeInsets.all(0.0),
    this.size,
    this.customSize,
    this.type,
    this.onTap,
    this.customColor,
  }) : super(key: key);
  final Function()? onTap;
  final String icon;
  final PineIconSize? size;
  final PineThemeTypes? type;
  final double? customSize;
  final EdgeInsetsGeometry padding;
  final Color? customColor;

  @override
  Widget build(BuildContext context) {
    if (icon.isEmpty) return Container();
    return InkWell(
      onTap: onTap,
      child: Padding(
        padding: padding,
        child: SvgPicture.asset(
          _icons[icon].toString(),
          color: customColor ?? _getColor(type),
          height: size == null ? customSize : _getSize(size),
          width: size == null ? customSize : _getSize(size),
        ),
      ),
    );
  }

  Color? _getColor(type) {
    if (type == null) return null;
    return _iconColor[type];
  }

  double? _getSize(size) {
    if (size == null) return null;
    return _iconSize[size];
  }
}
